---
output:
  html_document:
    theme: readable
    highlight: tango
    
---

# Aiyana Koka Willard

### Cultural and Evolutionary Psychologist 
####Specializing in Religion and Supernatural Beliefs

Current publications

  * Purzycki, B. G., & Willard, A. K. (forthcoming). MCI Theory: A guide from the perplexed. Religion Brain and Behaviour. [PDF](img/PurzyckiWillardRBB-Final.pdf)
  * Willard, A. K. & Norenzayan, A. (2013). Cognitive Biases Explain Religious Belief, Paranormal Belief, and Belief in Life’s Purpose. Cognition 129, 379-391. [PDF](img/Cognition_2013_Willard.pdf)
  * Gervais, W., Willard, A. K., Norenzayan, A., & Henrich, J. (2011). The Cultural Transmission of Faith: Why natural intuitions and memory biases are necessary, but insufficient, to explain religious belief. Religion 41, 389-410. [PDF](img/Religion_2011_Gervais.pdf)

CV [PDF](img/Aiyana_Willard_CV-2014.pdf)

#### Other Information

This is my attempt to make a website using R-markdown. It is under construction. This site was created as a way to teach myself a few new skills, such as version control and markdown, not as a serious website. A serious website is coming soon. 